apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-trader-ingress
  namespace: trading
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "cloud-trader-ip"
    networking.gke.io/managed-certificates: "cloud-trader-cert"
spec:
  ingressClassName: gce
  rules:
  - host: api.sapphiretrade.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-trader-service
            port:
              number: 80
