global:
  scrape_interval: 15s

scrape_configs:
  - job_name: trader
    static_configs:
      - targets:
          -  host.docker.internal:8080
          -  host.docker.internal:8082
  - job_name: llama_cpp
    static_configs:
      - targets:
          - host.docker.internal:8081
  - job_name: model_serving
    static_configs:
      - targets:
          - host.docker.internal:8000

